version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - '127.0.0.1:60000:3000'
    env_file: .env-back
    working_dir: /api
    volumes:
      - .:/api

  db:
    image: postgres:14
    ports:
      - '127.0.0.1:60002:5432'
    env_file: .env-db
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - '127.0.0.1:60080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_USER: housing
      ADMINER_DEFAULT_DATABASE: housing
    logging:
      driver: none

volumes:
  db:
